### ISSUE TITLE
Packaged app doesn't show data

### ISSUE THREAD

**Issue by gregstewart** [gregstewart/hearthstone-tracker#33]

**Comment by gregstewart** [comment]
Now that we have logging I can see the error: 

```
{"message":"","type":"OpenError","name":"OpenError","cause":{},"stack":"OpenError: IO error: hearthstone-tracker-leveldb/LOCK: No such file or directory\n at /Users/gregstewart/Projects/github/hearthstone-tracker/builds/HearthstoneTracker-darwin-x64/HearthstoneTracker.app/Contents/Resources/app/node_modules/pouchdb/node_modules/levelup/lib/levelup.js:119:34\n at /Users/gregstewart/Projects/github/hearthstone-tracker/builds/HearthstoneTracker-darwin-x64/HearthstoneTracker.app/Contents/Resources/app/node_modules/pouchdb/node_modules/leveldown/node_modules/abstract-leveldown/abstract-leveldown.js:39:16","level":"error"}
```

**Comment by gregstewart** [comment]
Maybe specifying the path would help:

```
var MyPrefixedPouch = PouchDB.defaults({
  prefix: '/path/to/my/db/'
});
// db will be named '/path/to/my/db/dbname', useful for LevelDB
var myPrefixedPouch = new MyPrefixedPouch('dbname');
```

See: http://pouchdb.com/api.html#defaults

**Comment by gregstewart** [comment]
Or even simpler:

```
var pouch = new PouchDB('./path/to/db');
```

http://pouchdb.com/adapters.html#pouchdb_in_node_js

**Comment by gregstewart** [comment]
Should log the current working directory to figure out where we are actually at:

```
process.cwd()
```
